freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script: pkg install -y
    autoconf automake libtool m4 pkgconf
    atf
    lua52 lutok sqlite3

  script: |
    autoreconf -i -s
    ./configure
    make distcheck
