@c Copyright 2011 Google Inc.
@c All rights reserved.
@c
@c Redistribution and use in source and binary forms, with or without
@c modification, are permitted provided that the following conditions are
@c met:
@c
@c * Redistributions of source code must retain the above copyright
@c   notice, this list of conditions and the following disclaimer.
@c * Redistributions in binary form must reproduce the above copyright
@c   notice, this list of conditions and the following disclaimer in the
@c   documentation and/or other materials provided with the distribution.
@c * Neither the name of Google Inc. nor the names of its contributors
@c   may be used to endorse or promote products derived from this software
@c   without specific prior written permission.
@c
@c THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
@c "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
@c LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
@c A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
@c OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
@c SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
@c LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
@c DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
@c THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
@c (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
@c OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

@node Usage
@chapter Usage

@cindex usage

This chapter describes the functionality of the command-line interface
of @command{kyua}.

@menu
* Environment variables:: User-tunable varibles.
@end menu

@node Environment variables
@section Environment variables

@cindex environment
@cindex environment variables

The following environment variables are recognized by @command{kyua}.
In general, you should not have to set them.  They are provided to
override the value of built-in values.

@table @env
@item KYUA_CONFDIR
Path to the system-wide configuration files for @command{kyua}.

Defaults to @file{@value{KYUA_CONFDIR}}.

@item KYUA_DOCDIR
Path to the location of installed documentation.

Defaults to @file{@value{KYUA_DOCDIR}}.

@item KYUA_LUADIR
Path to the location of the installed Lua modules provided by @command{kyua}.

Defaults to @file{@value{KYUA_LUADIR}}.

@item TMPDIR
Path to the system-wide temporary directory.  @command{kyua} will use
this location to place the work directory of test cases, among other
things.

The default for this variable depends on the operating system.  In
general, it is @file{/tmp}.
@end table
